- platform: template
  lights:
    lounge:
      friendly_name: "Lounge"
      turn_on:
        service: shell_command.rako
        data_template:
          room: 17
          channel: 0
          level: 255
      turn_off:
        service: shell_command.rako
        data_template:
           room: 17
           channel: 0
           level: 0
      set_level:
        service: shell_command.rako
        data_template:
          room: 17
          channel: 0
          level: "{{brightness}}"
