- platform: template
  lights:
    master_ensuite:
      friendly_name: "Master Bedroom Ensuite"
      turn_on:
        service: shell_command.rako
        data_template:
          room: 33
          channel: 0
          level: 255
      turn_off:
        service: shell_command.rako
        data_template:
           room: 33
           channel: 0
           level: 0
      set_level:
        service: shell_command.rako
        data_template:
          room: 33
          channel: 0
          level: "{{brightness}}"
